name: build test and deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository on the machine
        uses: actions/checkout@v4
      - name: Use Node.js version 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install the dependencies
        run: npm install
      - name: Start the server
        run: npm start & 
      - name: Run the unit tests
        run: npm run test:unit
      - name: Show SoftUni username
        run: echo "nikolayvf"
